[package]
name = "nft-mining"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = "21.1.0-rc.1"


[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }